/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildMembers implements Serializable {

    private static final long serialVersionUID = 1562728989;

    private final Integer id;
    private final Integer guild;
    private final String  name;
    private final Short   level;
    private final Short   skin;
    private final Byte    rank;
    private final Long    experienceGived;
    private final Byte    percentGived;
    private final Integer rights;
    private final Byte    alignment;
    private final String  lastconnection;

    public GuildMembers(GuildMembers value) {
        this.id = value.id;
        this.guild = value.guild;
        this.name = value.name;
        this.level = value.level;
        this.skin = value.skin;
        this.rank = value.rank;
        this.experienceGived = value.experienceGived;
        this.percentGived = value.percentGived;
        this.rights = value.rights;
        this.alignment = value.alignment;
        this.lastconnection = value.lastconnection;
    }

    public GuildMembers(
        Integer id,
        Integer guild,
        String  name,
        Short   level,
        Short   skin,
        Byte    rank,
        Long    experienceGived,
        Byte    percentGived,
        Integer rights,
        Byte    alignment,
        String  lastconnection
    ) {
        this.id = id;
        this.guild = guild;
        this.name = name;
        this.level = level;
        this.skin = skin;
        this.rank = rank;
        this.experienceGived = experienceGived;
        this.percentGived = percentGived;
        this.rights = rights;
        this.alignment = alignment;
        this.lastconnection = lastconnection;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getGuild() {
        return this.guild;
    }

    public String getName() {
        return this.name;
    }

    public Short getLevel() {
        return this.level;
    }

    public Short getSkin() {
        return this.skin;
    }

    public Byte getRank() {
        return this.rank;
    }

    public Long getExperienceGived() {
        return this.experienceGived;
    }

    public Byte getPercentGived() {
        return this.percentGived;
    }

    public Integer getRights() {
        return this.rights;
    }

    public Byte getAlignment() {
        return this.alignment;
    }

    public String getLastconnection() {
        return this.lastconnection;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GuildMembers (");

        sb.append(id);
        sb.append(", ").append(guild);
        sb.append(", ").append(name);
        sb.append(", ").append(level);
        sb.append(", ").append(skin);
        sb.append(", ").append(rank);
        sb.append(", ").append(experienceGived);
        sb.append(", ").append(percentGived);
        sb.append(", ").append(rights);
        sb.append(", ").append(alignment);
        sb.append(", ").append(lastconnection);

        sb.append(")");
        return sb.toString();
    }
}
