/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HousesData implements Serializable {

    private static final long serialVersionUID = -1420569157;

    private final Short   id;
    private final Integer owner;
    private final Long    sale;
    private final Integer guildId;
    private final Integer access;
    private final String  key;
    private final Integer guildRights;

    public HousesData(HousesData value) {
        this.id = value.id;
        this.owner = value.owner;
        this.sale = value.sale;
        this.guildId = value.guildId;
        this.access = value.access;
        this.key = value.key;
        this.guildRights = value.guildRights;
    }

    public HousesData(
        Short   id,
        Integer owner,
        Long    sale,
        Integer guildId,
        Integer access,
        String  key,
        Integer guildRights
    ) {
        this.id = id;
        this.owner = owner;
        this.sale = sale;
        this.guildId = guildId;
        this.access = access;
        this.key = key;
        this.guildRights = guildRights;
    }

    public Short getId() {
        return this.id;
    }

    public Integer getOwner() {
        return this.owner;
    }

    public Long getSale() {
        return this.sale;
    }

    public Integer getGuildId() {
        return this.guildId;
    }

    public Integer getAccess() {
        return this.access;
    }

    public String getKey() {
        return this.key;
    }

    public Integer getGuildRights() {
        return this.guildRights;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HousesData (");

        sb.append(id);
        sb.append(", ").append(owner);
        sb.append(", ").append(sale);
        sb.append(", ").append(guildId);
        sb.append(", ").append(access);
        sb.append(", ").append(key);
        sb.append(", ").append(guildRights);

        sb.append(")");
        return sb.toString();
    }
}
