/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobsData implements Serializable {

    private static final long serialVersionUID = 219027270;

    private final Integer id;
    private final String  name;
    private final String  tools;
    private final String  crafts;
    private final String  skills;
    private final String  ap;

    public JobsData(JobsData value) {
        this.id = value.id;
        this.name = value.name;
        this.tools = value.tools;
        this.crafts = value.crafts;
        this.skills = value.skills;
        this.ap = value.ap;
    }

    public JobsData(
        Integer id,
        String  name,
        String  tools,
        String  crafts,
        String  skills,
        String  ap
    ) {
        this.id = id;
        this.name = name;
        this.tools = tools;
        this.crafts = crafts;
        this.skills = skills;
        this.ap = ap;
    }

    public Integer getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public String getTools() {
        return this.tools;
    }

    public String getCrafts() {
        return this.crafts;
    }

    public String getSkills() {
        return this.skills;
    }

    public String getAp() {
        return this.ap;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JobsData (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(tools);
        sb.append(", ").append(crafts);
        sb.append(", ").append(skills);
        sb.append(", ").append(ap);

        sb.append(")");
        return sb.toString();
    }
}
