/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Spells implements Serializable {

    private static final long serialVersionUID = -15638842;

    private final Short   id;
    private final Short   spell;
    private final Byte    level;
    private final Byte    position;
    private final Integer owner;

    public Spells(Spells value) {
        this.id = value.id;
        this.spell = value.spell;
        this.level = value.level;
        this.position = value.position;
        this.owner = value.owner;
    }

    public Spells(
        Short   id,
        Short   spell,
        Byte    level,
        Byte    position,
        Integer owner
    ) {
        this.id = id;
        this.spell = spell;
        this.level = level;
        this.position = position;
        this.owner = owner;
    }

    public Short getId() {
        return this.id;
    }

    public Short getSpell() {
        return this.spell;
    }

    public Byte getLevel() {
        return this.level;
    }

    public Byte getPosition() {
        return this.position;
    }

    public Integer getOwner() {
        return this.owner;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Spells (");

        sb.append(id);
        sb.append(", ").append(spell);
        sb.append(", ").append(level);
        sb.append(", ").append(position);
        sb.append(", ").append(owner);

        sb.append(")");
        return sb.toString();
    }
}
