/**
 * This class is generated by jOOQ
 */
package org.graviton.database.jooq;


import org.graviton.database.jooq.tables.Accounts;
import org.graviton.database.jooq.tables.Players;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Login extends SchemaImpl {

	/**
	 * The reference instance of <code>login</code>
	 */
	public static final Login LOGIN = new Login();
	private static final long serialVersionUID = -1916004087;

	/**
	 * No further instances allowed
	 */
	private Login() {
		super("login");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Accounts.ACCOUNTS,
			Players.PLAYERS);
	}
}
