/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables.records;


import javax.annotation.Generated;

import org.graviton.database.jooq.game.tables.Guilds;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildsRecord extends UpdatableRecordImpl<GuildsRecord> implements Record11<Integer, String, String, Short, Long, Integer, Integer, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = -46335783;

    /**
     * Setter for <code>game.guilds.id</code>.
     */
    public GuildsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.guilds.name</code>.
     */
    public GuildsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>game.guilds.emblem</code>.
     */
    public GuildsRecord setEmblem(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.emblem</code>.
     */
    public String getEmblem() {
        return (String) get(2);
    }

    /**
     * Setter for <code>game.guilds.level</code>.
     */
    public GuildsRecord setLevel(Short value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.level</code>.
     */
    public Short getLevel() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>game.guilds.experience</code>.
     */
    public GuildsRecord setExperience(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.experience</code>.
     */
    public Long getExperience() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>game.guilds.capital</code>.
     */
    public GuildsRecord setCapital(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.capital</code>.
     */
    public Integer getCapital() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>game.guilds.limit</code>.
     */
    public GuildsRecord setLimit(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.limit</code>.
     */
    public Integer getLimit() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>game.guilds.spells</code>.
     */
    public GuildsRecord setSpells(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.spells</code>.
     */
    public String getSpells() {
        return (String) get(7);
    }

    /**
     * Setter for <code>game.guilds.pods</code>.
     */
    public GuildsRecord setPods(Integer value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.pods</code>.
     */
    public Integer getPods() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>game.guilds.prospection</code>.
     */
    public GuildsRecord setProspection(Integer value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.prospection</code>.
     */
    public Integer getProspection() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>game.guilds.wisdom</code>.
     */
    public GuildsRecord setWisdom(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>game.guilds.wisdom</code>.
     */
    public Integer getWisdom() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, Short, Long, Integer, Integer, String, Integer, Integer, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, String, Short, Long, Integer, Integer, String, Integer, Integer, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Guilds.GUILDS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Guilds.GUILDS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Guilds.GUILDS.EMBLEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field4() {
        return Guilds.GUILDS.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Guilds.GUILDS.EXPERIENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Guilds.GUILDS.CAPITAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Guilds.GUILDS.LIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Guilds.GUILDS.SPELLS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Guilds.GUILDS.PODS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Guilds.GUILDS.PROSPECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Guilds.GUILDS.WISDOM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmblem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value4() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getExperience();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCapital();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSpells();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPods();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getProspection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getWisdom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value3(String value) {
        setEmblem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value4(Short value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value5(Long value) {
        setExperience(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value6(Integer value) {
        setCapital(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value7(Integer value) {
        setLimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value8(String value) {
        setSpells(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value9(Integer value) {
        setPods(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value10(Integer value) {
        setProspection(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value11(Integer value) {
        setWisdom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord values(Integer value1, String value2, String value3, Short value4, Long value5, Integer value6, Integer value7, String value8, Integer value9, Integer value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildsRecord
     */
    public GuildsRecord() {
        super(Guilds.GUILDS);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(Integer id, String name, String emblem, Short level, Long experience, Integer capital, Integer limit, String spells, Integer pods, Integer prospection, Integer wisdom) {
        super(Guilds.GUILDS);

        set(0, id);
        set(1, name);
        set(2, emblem);
        set(3, level);
        set(4, experience);
        set(5, capital);
        set(6, limit);
        set(7, spells);
        set(8, pods);
        set(9, prospection);
        set(10, wisdom);
    }
}
