/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables.records;


import javax.annotation.Generated;

import org.graviton.database.jooq.game.tables.HousesData;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HousesDataRecord extends UpdatableRecordImpl<HousesDataRecord> implements Record7<Short, Integer, Long, Integer, Integer, String, UInteger> {

    private static final long serialVersionUID = 696098787;

    /**
     * Setter for <code>game.houses_data.id</code>.
     */
    public HousesDataRecord setId(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>game.houses_data.id</code>.
     */
    public Short getId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>game.houses_data.owner</code>.
     */
    public HousesDataRecord setOwner(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>game.houses_data.owner</code>.
     */
    public Integer getOwner() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.houses_data.sale</code>.
     */
    public HousesDataRecord setSale(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>game.houses_data.sale</code>.
     */
    public Long getSale() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>game.houses_data.guild_id</code>.
     */
    public HousesDataRecord setGuildId(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>game.houses_data.guild_id</code>.
     */
    public Integer getGuildId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>game.houses_data.access</code>.
     */
    public HousesDataRecord setAccess(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>game.houses_data.access</code>.
     */
    public Integer getAccess() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>game.houses_data.key</code>.
     */
    public HousesDataRecord setKey(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>game.houses_data.key</code>.
     */
    public String getKey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>game.houses_data.guild_rights</code>.
     */
    public HousesDataRecord setGuildRights(UInteger value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>game.houses_data.guild_rights</code>.
     */
    public UInteger getGuildRights() {
        return (UInteger) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Short> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Short, Integer, Long, Integer, Integer, String, UInteger> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Short, Integer, Long, Integer, Integer, String, UInteger> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return HousesData.HOUSES_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return HousesData.HOUSES_DATA.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return HousesData.HOUSES_DATA.SALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return HousesData.HOUSES_DATA.GUILD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return HousesData.HOUSES_DATA.ACCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return HousesData.HOUSES_DATA.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return HousesData.HOUSES_DATA.GUILD_RIGHTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getSale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getGuildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getGuildRights();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HousesDataRecord value1(Short value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HousesDataRecord value2(Integer value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HousesDataRecord value3(Long value) {
        setSale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HousesDataRecord value4(Integer value) {
        setGuildId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HousesDataRecord value5(Integer value) {
        setAccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HousesDataRecord value6(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HousesDataRecord value7(UInteger value) {
        setGuildRights(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HousesDataRecord values(Short value1, Integer value2, Long value3, Integer value4, Integer value5, String value6, UInteger value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HousesDataRecord
     */
    public HousesDataRecord() {
        super(HousesData.HOUSES_DATA);
    }

    /**
     * Create a detached, initialised HousesDataRecord
     */
    public HousesDataRecord(Short id, Integer owner, Long sale, Integer guildId, Integer access, String key, UInteger guildRights) {
        super(HousesData.HOUSES_DATA);

        set(0, id);
        set(1, owner);
        set(2, sale);
        set(3, guildId);
        set(4, access);
        set(5, key);
        set(6, guildRights);
    }
}
