/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables.records;


import javax.annotation.Generated;

import org.graviton.database.jooq.game.tables.JobsData;
import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobsDataRecord extends TableRecordImpl<JobsDataRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = -82329942;

    /**
     * Setter for <code>game.jobs_data.id</code>.
     */
    public JobsDataRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>game.jobs_data.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.jobs_data.name</code>.
     */
    public JobsDataRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>game.jobs_data.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>game.jobs_data.tools</code>. outils utilisables
     */
    public JobsDataRecord setTools(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>game.jobs_data.tools</code>. outils utilisables
     */
    public String getTools() {
        return (String) get(2);
    }

    /**
     * Setter for <code>game.jobs_data.crafts</code>. templateID craftable
     */
    public JobsDataRecord setCrafts(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>game.jobs_data.crafts</code>. templateID craftable
     */
    public String getCrafts() {
        return (String) get(3);
    }

    /**
     * Setter for <code>game.jobs_data.skills</code>.
     */
    public JobsDataRecord setSkills(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>game.jobs_data.skills</code>.
     */
    public String getSkills() {
        return (String) get(4);
    }

    /**
     * Setter for <code>game.jobs_data.AP</code>.
     */
    public JobsDataRecord setAp(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>game.jobs_data.AP</code>.
     */
    public String getAp() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JobsData.JOBS_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JobsData.JOBS_DATA.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JobsData.JOBS_DATA.TOOLS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JobsData.JOBS_DATA.CRAFTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return JobsData.JOBS_DATA.SKILLS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return JobsData.JOBS_DATA.AP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTools();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCrafts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSkills();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsDataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsDataRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsDataRecord value3(String value) {
        setTools(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsDataRecord value4(String value) {
        setCrafts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsDataRecord value5(String value) {
        setSkills(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsDataRecord value6(String value) {
        setAp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsDataRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobsDataRecord
     */
    public JobsDataRecord() {
        super(JobsData.JOBS_DATA);
    }

    /**
     * Create a detached, initialised JobsDataRecord
     */
    public JobsDataRecord(Integer id, String name, String tools, String crafts, String skills, String ap) {
        super(JobsData.JOBS_DATA);

        set(0, id);
        set(1, name);
        set(2, tools);
        set(3, crafts);
        set(4, skills);
        set(5, ap);
    }
}
