/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables.records;


import javax.annotation.Generated;

import org.graviton.database.jooq.game.tables.Spells;
import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpellsRecord extends TableRecordImpl<SpellsRecord> implements Record5<Short, Short, Byte, Byte, Integer> {

    private static final long serialVersionUID = -1858779957;

    /**
     * Setter for <code>game.spells.id</code>.
     */
    public SpellsRecord setId(Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>game.spells.id</code>.
     */
    public Short getId() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>game.spells.spell</code>.
     */
    public SpellsRecord setSpell(Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>game.spells.spell</code>.
     */
    public Short getSpell() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>game.spells.level</code>.
     */
    public SpellsRecord setLevel(Byte value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>game.spells.level</code>.
     */
    public Byte getLevel() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>game.spells.position</code>.
     */
    public SpellsRecord setPosition(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>game.spells.position</code>.
     */
    public Byte getPosition() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>game.spells.owner</code>.
     */
    public SpellsRecord setOwner(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>game.spells.owner</code>.
     */
    public Integer getOwner() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Short, Short, Byte, Byte, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Short, Short, Byte, Byte, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field1() {
        return Spells.SPELLS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field2() {
        return Spells.SPELLS.SPELL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return Spells.SPELLS.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Spells.SPELLS.POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Spells.SPELLS.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value2() {
        return getSpell();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpellsRecord value1(Short value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpellsRecord value2(Short value) {
        setSpell(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpellsRecord value3(Byte value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpellsRecord value4(Byte value) {
        setPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpellsRecord value5(Integer value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SpellsRecord values(Short value1, Short value2, Byte value3, Byte value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpellsRecord
     */
    public SpellsRecord() {
        super(Spells.SPELLS);
    }

    /**
     * Create a detached, initialised SpellsRecord
     */
    public SpellsRecord(Short id, Short spell, Byte level, Byte position, Integer owner) {
        super(Spells.SPELLS);

        set(0, id);
        set(1, spell);
        set(2, level);
        set(3, position);
        set(4, owner);
    }
}
