/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables.records;


import javax.annotation.Generated;

import org.graviton.database.jooq.game.tables.SubareaData;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubareaDataRecord extends UpdatableRecordImpl<SubareaDataRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 897547657;

    /**
     * Setter for <code>game.subarea_data.id</code>.
     */
    public SubareaDataRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>game.subarea_data.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game.subarea_data.alignement</code>.
     */
    public SubareaDataRecord setAlignement(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>game.subarea_data.alignement</code>.
     */
    public Integer getAlignement() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>game.subarea_data.conquistable</code>.
     */
    public SubareaDataRecord setConquistable(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>game.subarea_data.conquistable</code>.
     */
    public Integer getConquistable() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>game.subarea_data.prisme</code>.
     */
    public SubareaDataRecord setPrisme(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>game.subarea_data.prisme</code>.
     */
    public Integer getPrisme() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SubareaData.SUBAREA_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SubareaData.SUBAREA_DATA.ALIGNEMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SubareaData.SUBAREA_DATA.CONQUISTABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SubareaData.SUBAREA_DATA.PRISME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAlignement();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getConquistable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPrisme();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubareaDataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubareaDataRecord value2(Integer value) {
        setAlignement(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubareaDataRecord value3(Integer value) {
        setConquistable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubareaDataRecord value4(Integer value) {
        setPrisme(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SubareaDataRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubareaDataRecord
     */
    public SubareaDataRecord() {
        super(SubareaData.SUBAREA_DATA);
    }

    /**
     * Create a detached, initialised SubareaDataRecord
     */
    public SubareaDataRecord(Integer id, Integer alignement, Integer conquistable, Integer prisme) {
        super(SubareaData.SUBAREA_DATA);

        set(0, id);
        set(1, alignement);
        set(2, conquistable);
        set(3, prisme);
    }
}
