/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.login.tables.records;


import javax.annotation.Generated;

import org.graviton.database.jooq.login.tables.Players;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayersRecord extends UpdatableRecordImpl<PlayersRecord> {

    private static final long serialVersionUID = 1612595245;

    /**
     * Setter for <code>login.players.id</code>.
     */
    public PlayersRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>login.players.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>login.players.owner</code>.
     */
    public PlayersRecord setOwner(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>login.players.owner</code>.
     */
    public Integer getOwner() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>login.players.name</code>.
     */
    public PlayersRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>login.players.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>login.players.breed</code>.
     */
    public PlayersRecord setBreed(Byte value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>login.players.breed</code>.
     */
    public Byte getBreed() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>login.players.sex</code>.
     */
    public PlayersRecord setSex(Byte value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>login.players.sex</code>.
     */
    public Byte getSex() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>login.players.skin</code>.
     */
    public PlayersRecord setSkin(Short value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>login.players.skin</code>.
     */
    public Short getSkin() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>login.players.size</code>.
     */
    public PlayersRecord setSize(Short value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>login.players.size</code>.
     */
    public Short getSize() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>login.players.colors</code>.
     */
    public PlayersRecord setColors(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>login.players.colors</code>.
     */
    public String getColors() {
        return (String) get(7);
    }

    /**
     * Setter for <code>login.players.level</code>.
     */
    public PlayersRecord setLevel(Short value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>login.players.level</code>.
     */
    public Short getLevel() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>login.players.experience</code>.
     */
    public PlayersRecord setExperience(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>login.players.experience</code>.
     */
    public Long getExperience() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>login.players.title</code>.
     */
    public PlayersRecord setTitle(Byte value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>login.players.title</code>.
     */
    public Byte getTitle() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>login.players.alignment</code>.
     */
    public PlayersRecord setAlignment(Byte value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>login.players.alignment</code>.
     */
    public Byte getAlignment() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>login.players.honor</code>.
     */
    public PlayersRecord setHonor(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>login.players.honor</code>.
     */
    public Integer getHonor() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>login.players.dishonnor</code>.
     */
    public PlayersRecord setDishonnor(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>login.players.dishonnor</code>.
     */
    public Integer getDishonnor() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>login.players.pvp_enabled</code>.
     */
    public PlayersRecord setPvpEnabled(Byte value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>login.players.pvp_enabled</code>.
     */
    public Byte getPvpEnabled() {
        return (Byte) get(14);
    }

    /**
     * Setter for <code>login.players.kamas</code>.
     */
    public PlayersRecord setKamas(Long value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>login.players.kamas</code>.
     */
    public Long getKamas() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>login.players.map</code>.
     */
    public PlayersRecord setMap(Integer value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>login.players.map</code>.
     */
    public Integer getMap() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>login.players.cell</code>.
     */
    public PlayersRecord setCell(Short value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>login.players.cell</code>.
     */
    public Short getCell() {
        return (Short) get(17);
    }

    /**
     * Setter for <code>login.players.orientation</code>.
     */
    public PlayersRecord setOrientation(Byte value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>login.players.orientation</code>.
     */
    public Byte getOrientation() {
        return (Byte) get(18);
    }

    /**
     * Setter for <code>login.players.waypoints</code>.
     */
    public PlayersRecord setWaypoints(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>login.players.waypoints</code>.
     */
    public String getWaypoints() {
        return (String) get(19);
    }

    /**
     * Setter for <code>login.players.stat_points</code>.
     */
    public PlayersRecord setStatPoints(Short value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>login.players.stat_points</code>.
     */
    public Short getStatPoints() {
        return (Short) get(20);
    }

    /**
     * Setter for <code>login.players.spell_points</code>.
     */
    public PlayersRecord setSpellPoints(Short value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>login.players.spell_points</code>.
     */
    public Short getSpellPoints() {
        return (Short) get(21);
    }

    /**
     * Setter for <code>login.players.energy</code>.
     */
    public PlayersRecord setEnergy(Short value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>login.players.energy</code>.
     */
    public Short getEnergy() {
        return (Short) get(22);
    }

    /**
     * Setter for <code>login.players.life</code>.
     */
    public PlayersRecord setLife(Byte value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>login.players.life</code>.
     */
    public Byte getLife() {
        return (Byte) get(23);
    }

    /**
     * Setter for <code>login.players.vitality</code>.
     */
    public PlayersRecord setVitality(Short value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>login.players.vitality</code>.
     */
    public Short getVitality() {
        return (Short) get(24);
    }

    /**
     * Setter for <code>login.players.wisdom</code>.
     */
    public PlayersRecord setWisdom(Short value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>login.players.wisdom</code>.
     */
    public Short getWisdom() {
        return (Short) get(25);
    }

    /**
     * Setter for <code>login.players.strength</code>.
     */
    public PlayersRecord setStrength(Short value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>login.players.strength</code>.
     */
    public Short getStrength() {
        return (Short) get(26);
    }

    /**
     * Setter for <code>login.players.intelligence</code>.
     */
    public PlayersRecord setIntelligence(Short value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>login.players.intelligence</code>.
     */
    public Short getIntelligence() {
        return (Short) get(27);
    }

    /**
     * Setter for <code>login.players.chance</code>.
     */
    public PlayersRecord setChance(Short value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>login.players.chance</code>.
     */
    public Short getChance() {
        return (Short) get(28);
    }

    /**
     * Setter for <code>login.players.agility</code>.
     */
    public PlayersRecord setAgility(Short value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>login.players.agility</code>.
     */
    public Short getAgility() {
        return (Short) get(29);
    }

    /**
     * Setter for <code>login.players.guild</code>.
     */
    public PlayersRecord setGuild(Integer value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>login.players.guild</code>.
     */
    public Integer getGuild() {
        return (Integer) get(30);
    }

    /**
     * Setter for <code>login.players.server</code>.
     */
    public PlayersRecord setServer(Byte value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>login.players.server</code>.
     */
    public Byte getServer() {
        return (Byte) get(31);
    }

    /**
     * Setter for <code>login.players.savedLocation</code>.
     */
    public PlayersRecord setSavedlocation(String value) {
        set(32, value);
        return this;
    }

    /**
     * Getter for <code>login.players.savedLocation</code>.
     */
    public String getSavedlocation() {
        return (String) get(32);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayersRecord
     */
    public PlayersRecord() {
        super(Players.PLAYERS);
    }

    /**
     * Create a detached, initialised PlayersRecord
     */
    public PlayersRecord(Integer id, Integer owner, String name, Byte breed, Byte sex, Short skin, Short size, String colors, Short level, Long experience, Byte title, Byte alignment, Integer honor, Integer dishonnor, Byte pvpEnabled, Long kamas, Integer map, Short cell, Byte orientation, String waypoints, Short statPoints, Short spellPoints, Short energy, Byte life, Short vitality, Short wisdom, Short strength, Short intelligence, Short chance, Short agility, Integer guild, Byte server, String savedlocation) {
        super(Players.PLAYERS);

        set(0, id);
        set(1, owner);
        set(2, name);
        set(3, breed);
        set(4, sex);
        set(5, skin);
        set(6, size);
        set(7, colors);
        set(8, level);
        set(9, experience);
        set(10, title);
        set(11, alignment);
        set(12, honor);
        set(13, dishonnor);
        set(14, pvpEnabled);
        set(15, kamas);
        set(16, map);
        set(17, cell);
        set(18, orientation);
        set(19, waypoints);
        set(20, statPoints);
        set(21, spellPoints);
        set(22, energy);
        set(23, life);
        set(24, vitality);
        set(25, wisdom);
        set(26, strength);
        set(27, intelligence);
        set(28, chance);
        set(29, agility);
        set(30, guild);
        set(31, server);
        set(32, savedlocation);
    }
}
