/**
 * This class is generated by jOOQ
 */
package org.graviton.database.jooq.login.tables.records;


import org.graviton.database.jooq.login.tables.Players;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.5"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PlayersRecord extends UpdatableRecordImpl<PlayersRecord> {

    private static final long serialVersionUID = -1713938747;

    /**
     * Create a detached PlayersRecord
     */
    public PlayersRecord() {
        super(Players.PLAYERS);
    }

    /**
     * Create a detached, initialised PlayersRecord
     */
    public PlayersRecord(Integer id, Integer owner, String name, Byte breed, Byte sex, Short skin, Short size, String colors, Byte level, Long experience, Long kamas, Integer map, Short cell, Byte orientation, String waypoints, Short statPoints, Short spellPoints, Short energy, Byte life, Short vitality, Short wisdom, Short strength, Short intelligence, Short chance, Short agility, Byte server) {
        super(Players.PLAYERS);

        set(0, id);
        set(1, owner);
        set(2, name);
        set(3, breed);
        set(4, sex);
        set(5, skin);
        set(6, size);
        set(7, colors);
        set(8, level);
        set(9, experience);
        set(10, kamas);
        set(11, map);
        set(12, cell);
        set(13, orientation);
        set(14, waypoints);
        set(15, statPoints);
        set(16, spellPoints);
        set(17, energy);
        set(18, life);
        set(19, vitality);
        set(20, wisdom);
        set(21, strength);
        set(22, intelligence);
        set(23, chance);
        set(24, agility);
        set(25, server);
    }

    /**
     * Getter for <code>login.players.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>login.players.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>login.players.owner</code>.
     */
    public Integer getOwner() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>login.players.owner</code>.
     */
    public void setOwner(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>login.players.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>login.players.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>login.players.breed</code>.
     */
    public Byte getBreed() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>login.players.breed</code>.
     */
    public void setBreed(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>login.players.sex</code>.
     */
    public Byte getSex() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>login.players.sex</code>.
     */
    public void setSex(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>login.players.skin</code>.
     */
    public Short getSkin() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>login.players.skin</code>.
     */
    public void setSkin(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>login.players.size</code>.
     */
    public Short getSize() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>login.players.size</code>.
     */
    public void setSize(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>login.players.colors</code>.
     */
    public String getColors() {
        return (String) get(7);
    }

    /**
     * Setter for <code>login.players.colors</code>.
     */
    public void setColors(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>login.players.level</code>.
     */
    public Byte getLevel() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>login.players.level</code>.
     */
    public void setLevel(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>login.players.experience</code>.
     */
    public Long getExperience() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>login.players.experience</code>.
     */
    public void setExperience(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>login.players.kamas</code>.
     */
    public Long getKamas() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>login.players.kamas</code>.
     */
    public void setKamas(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>login.players.map</code>.
     */
    public Integer getMap() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>login.players.map</code>.
     */
    public void setMap(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>login.players.cell</code>.
     */
    public Short getCell() {
        return (Short) get(12);
    }

    /**
     * Setter for <code>login.players.cell</code>.
     */
    public void setCell(Short value) {
        set(12, value);
    }

    /**
     * Getter for <code>login.players.orientation</code>.
     */
    public Byte getOrientation() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>login.players.orientation</code>.
     */
    public void setOrientation(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>login.players.waypoints</code>.
     */
    public String getWaypoints() {
        return (String) get(14);
    }

    /**
     * Setter for <code>login.players.waypoints</code>.
     */
    public void setWaypoints(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>login.players.stat_points</code>.
     */
    public Short getStatPoints() {
        return (Short) get(15);
    }

    /**
     * Setter for <code>login.players.stat_points</code>.
     */
    public void setStatPoints(Short value) {
        set(15, value);
    }

    /**
     * Getter for <code>login.players.spell_points</code>.
     */
    public Short getSpellPoints() {
        return (Short) get(16);
    }

    /**
     * Setter for <code>login.players.spell_points</code>.
     */
    public void setSpellPoints(Short value) {
        set(16, value);
    }

    /**
     * Getter for <code>login.players.energy</code>.
     */
    public Short getEnergy() {
        return (Short) get(17);
    }

    /**
     * Setter for <code>login.players.energy</code>.
     */
    public void setEnergy(Short value) {
        set(17, value);
    }

    /**
     * Getter for <code>login.players.life</code>.
     */
    public Byte getLife() {
        return (Byte) get(18);
    }

    /**
     * Setter for <code>login.players.life</code>.
     */
    public void setLife(Byte value) {
        set(18, value);
    }

    /**
     * Getter for <code>login.players.vitality</code>.
     */
    public Short getVitality() {
        return (Short) get(19);
    }

    /**
     * Setter for <code>login.players.vitality</code>.
     */
    public void setVitality(Short value) {
        set(19, value);
    }

    /**
     * Getter for <code>login.players.wisdom</code>.
     */
    public Short getWisdom() {
        return (Short) get(20);
    }

    /**
     * Setter for <code>login.players.wisdom</code>.
     */
    public void setWisdom(Short value) {
        set(20, value);
    }

    /**
     * Getter for <code>login.players.strength</code>.
     */
    public Short getStrength() {
        return (Short) get(21);
    }

    /**
     * Setter for <code>login.players.strength</code>.
     */
    public void setStrength(Short value) {
        set(21, value);
    }

    /**
     * Getter for <code>login.players.intelligence</code>.
     */
    public Short getIntelligence() {
        return (Short) get(22);
    }

    /**
     * Setter for <code>login.players.intelligence</code>.
     */
    public void setIntelligence(Short value) {
        set(22, value);
    }

    /**
     * Getter for <code>login.players.chance</code>.
     */
    public Short getChance() {
        return (Short) get(23);
    }

    /**
     * Setter for <code>login.players.chance</code>.
     */
    public void setChance(Short value) {
        set(23, value);
    }

    /**
     * Getter for <code>login.players.agility</code>.
     */
    public Short getAgility() {
        return (Short) get(24);
    }

    /**
     * Setter for <code>login.players.agility</code>.
     */
    public void setAgility(Short value) {
        set(24, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>login.players.server</code>.
     */
    public Byte getServer() {
        return (Byte) get(25);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>login.players.server</code>.
     */
    public void setServer(Byte value) {
        set(25, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }
}
