/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.graviton.database.jooq.game.tables.GuildMembers;
import org.graviton.database.jooq.game.tables.Guilds;
import org.graviton.database.jooq.game.tables.HousesData;
import org.graviton.database.jooq.game.tables.Items;
import org.graviton.database.jooq.game.tables.JobsData;
import org.graviton.database.jooq.game.tables.Spells;
import org.graviton.database.jooq.game.tables.SubareaData;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Game extends SchemaImpl {

    private static final long serialVersionUID = -749922279;

    /**
     * The reference instance of <code>game</code>
     */
    public static final Game GAME = new Game();

    /**
     * The table <code>game.guilds</code>.
     */
    public final Guilds GUILDS = org.graviton.database.jooq.game.tables.Guilds.GUILDS;

    /**
     * The table <code>game.guild_members</code>.
     */
    public final GuildMembers GUILD_MEMBERS = org.graviton.database.jooq.game.tables.GuildMembers.GUILD_MEMBERS;

    /**
     * The table <code>game.houses_data</code>.
     */
    public final HousesData HOUSES_DATA = org.graviton.database.jooq.game.tables.HousesData.HOUSES_DATA;

    /**
     * The table <code>game.items</code>.
     */
    public final Items ITEMS = org.graviton.database.jooq.game.tables.Items.ITEMS;

    /**
     * The table <code>game.jobs_data</code>.
     */
    public final JobsData JOBS_DATA = org.graviton.database.jooq.game.tables.JobsData.JOBS_DATA;

    /**
     * The table <code>game.spells</code>.
     */
    public final Spells SPELLS = org.graviton.database.jooq.game.tables.Spells.SPELLS;

    /**
     * The table <code>game.subarea_data</code>.
     */
    public final SubareaData SUBAREA_DATA = org.graviton.database.jooq.game.tables.SubareaData.SUBAREA_DATA;

    /**
     * No further instances allowed
     */
    private Game() {
        super("game", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Guilds.GUILDS,
            GuildMembers.GUILD_MEMBERS,
            HousesData.HOUSES_DATA,
            Items.ITEMS,
            JobsData.JOBS_DATA,
            Spells.SPELLS,
            SubareaData.SUBAREA_DATA);
    }
}
