/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game;


import javax.annotation.Generated;

import org.graviton.database.jooq.game.tables.GuildMembers;
import org.graviton.database.jooq.game.tables.Guilds;
import org.graviton.database.jooq.game.tables.HousesData;
import org.graviton.database.jooq.game.tables.Items;
import org.graviton.database.jooq.game.tables.JobsData;
import org.graviton.database.jooq.game.tables.SubareaData;
import org.graviton.database.jooq.game.tables.records.GuildMembersRecord;
import org.graviton.database.jooq.game.tables.records.GuildsRecord;
import org.graviton.database.jooq.game.tables.records.HousesDataRecord;
import org.graviton.database.jooq.game.tables.records.ItemsRecord;
import org.graviton.database.jooq.game.tables.records.JobsDataRecord;
import org.graviton.database.jooq.game.tables.records.SubareaDataRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>game</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GuildsRecord> KEY_GUILDS_PRIMARY = UniqueKeys0.KEY_GUILDS_PRIMARY;
    public static final UniqueKey<GuildMembersRecord> KEY_GUILD_MEMBERS_GUID = UniqueKeys0.KEY_GUILD_MEMBERS_GUID;
    public static final UniqueKey<HousesDataRecord> KEY_HOUSES_DATA_PRIMARY = UniqueKeys0.KEY_HOUSES_DATA_PRIMARY;
    public static final UniqueKey<ItemsRecord> KEY_ITEMS_GUID = UniqueKeys0.KEY_ITEMS_GUID;
    public static final UniqueKey<JobsDataRecord> KEY_JOBS_DATA_ID = UniqueKeys0.KEY_JOBS_DATA_ID;
    public static final UniqueKey<SubareaDataRecord> KEY_SUBAREA_DATA_PRIMARY = UniqueKeys0.KEY_SUBAREA_DATA_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<GuildsRecord> KEY_GUILDS_PRIMARY = createUniqueKey(Guilds.GUILDS, "KEY_guilds_PRIMARY", Guilds.GUILDS.ID);
        public static final UniqueKey<GuildMembersRecord> KEY_GUILD_MEMBERS_GUID = createUniqueKey(GuildMembers.GUILD_MEMBERS, "KEY_guild_members_guid", GuildMembers.GUILD_MEMBERS.ID);
        public static final UniqueKey<HousesDataRecord> KEY_HOUSES_DATA_PRIMARY = createUniqueKey(HousesData.HOUSES_DATA, "KEY_houses_data_PRIMARY", HousesData.HOUSES_DATA.ID);
        public static final UniqueKey<ItemsRecord> KEY_ITEMS_GUID = createUniqueKey(Items.ITEMS, "KEY_items_guid", Items.ITEMS.ID);
        public static final UniqueKey<JobsDataRecord> KEY_JOBS_DATA_ID = createUniqueKey(JobsData.JOBS_DATA, "KEY_jobs_data_id", JobsData.JOBS_DATA.ID);
        public static final UniqueKey<SubareaDataRecord> KEY_SUBAREA_DATA_PRIMARY = createUniqueKey(SubareaData.SUBAREA_DATA, "KEY_subarea_data_PRIMARY", SubareaData.SUBAREA_DATA.ID);
    }
}
