/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game;


import javax.annotation.Generated;

import org.graviton.database.jooq.game.tables.Banks;
import org.graviton.database.jooq.game.tables.GuildMembers;
import org.graviton.database.jooq.game.tables.Guilds;
import org.graviton.database.jooq.game.tables.HousesData;
import org.graviton.database.jooq.game.tables.Items;
import org.graviton.database.jooq.game.tables.Maps;
import org.graviton.database.jooq.game.tables.Merchant;
import org.graviton.database.jooq.game.tables.MountparkData;
import org.graviton.database.jooq.game.tables.QuestData;
import org.graviton.database.jooq.game.tables.QuestEtapes;
import org.graviton.database.jooq.game.tables.QuestObjectifs;
import org.graviton.database.jooq.game.tables.QuestPerso;
import org.graviton.database.jooq.game.tables.SellpointItems;
import org.graviton.database.jooq.game.tables.Spells;
import org.graviton.database.jooq.game.tables.SubareaData;
import org.graviton.database.jooq.game.tables.Trunks;


/**
 * Convenience access to all tables in game
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>game.banks</code>.
     */
    public static final Banks BANKS = org.graviton.database.jooq.game.tables.Banks.BANKS;

    /**
     * The table <code>game.guilds</code>.
     */
    public static final Guilds GUILDS = org.graviton.database.jooq.game.tables.Guilds.GUILDS;

    /**
     * The table <code>game.guild_members</code>.
     */
    public static final GuildMembers GUILD_MEMBERS = org.graviton.database.jooq.game.tables.GuildMembers.GUILD_MEMBERS;

    /**
     * The table <code>game.houses_data</code>.
     */
    public static final HousesData HOUSES_DATA = org.graviton.database.jooq.game.tables.HousesData.HOUSES_DATA;

    /**
     * The table <code>game.items</code>.
     */
    public static final Items ITEMS = org.graviton.database.jooq.game.tables.Items.ITEMS;

    /**
     * The table <code>game.maps</code>.
     */
    public static final Maps MAPS = org.graviton.database.jooq.game.tables.Maps.MAPS;

    /**
     * The table <code>game.merchant</code>.
     */
    public static final Merchant MERCHANT = org.graviton.database.jooq.game.tables.Merchant.MERCHANT;

    /**
     * The table <code>game.mountpark_data</code>.
     */
    public static final MountparkData MOUNTPARK_DATA = org.graviton.database.jooq.game.tables.MountparkData.MOUNTPARK_DATA;

    /**
     * The table <code>game.quest_data</code>.
     */
    public static final QuestData QUEST_DATA = org.graviton.database.jooq.game.tables.QuestData.QUEST_DATA;

    /**
     * The table <code>game.quest_etapes</code>.
     */
    public static final QuestEtapes QUEST_ETAPES = org.graviton.database.jooq.game.tables.QuestEtapes.QUEST_ETAPES;

    /**
     * The table <code>game.quest_objectifs</code>.
     */
    public static final QuestObjectifs QUEST_OBJECTIFS = org.graviton.database.jooq.game.tables.QuestObjectifs.QUEST_OBJECTIFS;

    /**
     * The table <code>game.quest_perso</code>.
     */
    public static final QuestPerso QUEST_PERSO = org.graviton.database.jooq.game.tables.QuestPerso.QUEST_PERSO;

    /**
     * The table <code>game.sellpoint_items</code>.
     */
    public static final SellpointItems SELLPOINT_ITEMS = org.graviton.database.jooq.game.tables.SellpointItems.SELLPOINT_ITEMS;

    /**
     * The table <code>game.spells</code>.
     */
    public static final Spells SPELLS = org.graviton.database.jooq.game.tables.Spells.SPELLS;

    /**
     * The table <code>game.subarea_data</code>.
     */
    public static final SubareaData SUBAREA_DATA = org.graviton.database.jooq.game.tables.SubareaData.SUBAREA_DATA;

    /**
     * The table <code>game.trunks</code>.
     */
    public static final Trunks TRUNKS = org.graviton.database.jooq.game.tables.Trunks.TRUNKS;
}
