/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game;


import javax.annotation.Generated;

import org.graviton.database.jooq.game.tables.GuildMembers;
import org.graviton.database.jooq.game.tables.Guilds;
import org.graviton.database.jooq.game.tables.HousesData;
import org.graviton.database.jooq.game.tables.Items;
import org.graviton.database.jooq.game.tables.JobsData;
import org.graviton.database.jooq.game.tables.Spells;
import org.graviton.database.jooq.game.tables.SubareaData;


/**
 * Convenience access to all tables in game
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>game.guilds</code>.
     */
    public static final Guilds GUILDS = org.graviton.database.jooq.game.tables.Guilds.GUILDS;

    /**
     * The table <code>game.guild_members</code>.
     */
    public static final GuildMembers GUILD_MEMBERS = org.graviton.database.jooq.game.tables.GuildMembers.GUILD_MEMBERS;

    /**
     * The table <code>game.houses_data</code>.
     */
    public static final HousesData HOUSES_DATA = org.graviton.database.jooq.game.tables.HousesData.HOUSES_DATA;

    /**
     * The table <code>game.items</code>.
     */
    public static final Items ITEMS = org.graviton.database.jooq.game.tables.Items.ITEMS;

    /**
     * The table <code>game.jobs_data</code>.
     */
    public static final JobsData JOBS_DATA = org.graviton.database.jooq.game.tables.JobsData.JOBS_DATA;

    /**
     * The table <code>game.spells</code>.
     */
    public static final Spells SPELLS = org.graviton.database.jooq.game.tables.Spells.SPELLS;

    /**
     * The table <code>game.subarea_data</code>.
     */
    public static final SubareaData SUBAREA_DATA = org.graviton.database.jooq.game.tables.SubareaData.SUBAREA_DATA;
}
