/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.graviton.database.jooq.game.Game;
import org.graviton.database.jooq.game.Keys;
import org.graviton.database.jooq.game.tables.records.GuildMembersRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildMembers extends TableImpl<GuildMembersRecord> {

    private static final long serialVersionUID = -440218597;

    /**
     * The reference instance of <code>game.guild_members</code>
     */
    public static final GuildMembers GUILD_MEMBERS = new GuildMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuildMembersRecord> getRecordType() {
        return GuildMembersRecord.class;
    }

    /**
     * The column <code>game.guild_members.id</code>.
     */
    public final TableField<GuildMembersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.guild_members.guild</code>.
     */
    public final TableField<GuildMembersRecord, Integer> GUILD = createField("guild", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.guild_members.name</code>.
     */
    public final TableField<GuildMembersRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>game.guild_members.level</code>.
     */
    public final TableField<GuildMembersRecord, Short> LEVEL = createField("level", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>game.guild_members.skin</code>.
     */
    public final TableField<GuildMembersRecord, Short> SKIN = createField("skin", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>game.guild_members.rank</code>.
     */
    public final TableField<GuildMembersRecord, Byte> RANK = createField("rank", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>game.guild_members.experience_gived</code>.
     */
    public final TableField<GuildMembersRecord, Long> EXPERIENCE_GIVED = createField("experience_gived", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>game.guild_members.percent_gived</code>.
     */
    public final TableField<GuildMembersRecord, Byte> PERCENT_GIVED = createField("percent_gived", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>game.guild_members.rights</code>.
     */
    public final TableField<GuildMembersRecord, Integer> RIGHTS = createField("rights", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.guild_members.alignment</code>.
     */
    public final TableField<GuildMembersRecord, Byte> ALIGNMENT = createField("alignment", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>game.guild_members.lastConnection</code>.
     */
    public final TableField<GuildMembersRecord, String> LASTCONNECTION = createField("lastConnection", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * Create a <code>game.guild_members</code> table reference
     */
    public GuildMembers() {
        this("guild_members", null);
    }

    /**
     * Create an aliased <code>game.guild_members</code> table reference
     */
    public GuildMembers(String alias) {
        this(alias, GUILD_MEMBERS);
    }

    private GuildMembers(String alias, Table<GuildMembersRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuildMembers(String alias, Table<GuildMembersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GuildMembersRecord>> getKeys() {
        return Arrays.<UniqueKey<GuildMembersRecord>>asList(Keys.KEY_GUILD_MEMBERS_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildMembers as(String alias) {
        return new GuildMembers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuildMembers rename(String name) {
        return new GuildMembers(name, null);
    }
}
