/*
 * This file is generated by jOOQ.
*/
package org.graviton.database.jooq.game.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.graviton.database.jooq.game.Game;
import org.graviton.database.jooq.game.Keys;
import org.graviton.database.jooq.game.tables.records.JobsDataRecord;
import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobsData extends TableImpl<JobsDataRecord> {

    private static final long serialVersionUID = -1426002071;

    /**
     * The reference instance of <code>game.jobs_data</code>
     */
    public static final JobsData JOBS_DATA = new JobsData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobsDataRecord> getRecordType() {
        return JobsDataRecord.class;
    }

    /**
     * The column <code>game.jobs_data.id</code>.
     */
    public final TableField<JobsDataRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game.jobs_data.name</code>.
     */
    public final TableField<JobsDataRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>game.jobs_data.tools</code>. outils utilisables
     */
    public final TableField<JobsDataRecord, String> TOOLS = createField("tools", org.jooq.impl.SQLDataType.VARCHAR.length(300).nullable(false), this, "outils utilisables");

    /**
     * The column <code>game.jobs_data.crafts</code>. templateID craftable
     */
    public final TableField<JobsDataRecord, String> CRAFTS = createField("crafts", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "templateID craftable");

    /**
     * The column <code>game.jobs_data.skills</code>.
     */
    public final TableField<JobsDataRecord, String> SKILLS = createField("skills", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>game.jobs_data.AP</code>.
     */
    public final TableField<JobsDataRecord, String> AP = createField("AP", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>game.jobs_data</code> table reference
     */
    public JobsData() {
        this("jobs_data", null);
    }

    /**
     * Create an aliased <code>game.jobs_data</code> table reference
     */
    public JobsData(String alias) {
        this(alias, JOBS_DATA);
    }

    private JobsData(String alias, Table<JobsDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private JobsData(String alias, Table<JobsDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Game.GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JobsDataRecord>> getKeys() {
        return Arrays.<UniqueKey<JobsDataRecord>>asList(Keys.KEY_JOBS_DATA_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobsData as(String alias) {
        return new JobsData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JobsData rename(String name) {
        return new JobsData(name, null);
    }
}
